sudo:false
language: python
python:
  - 3.5
  - 3.6
matrix:
  include:
  - python: 3.7
    dist: xenial
    sudo: true
install:
  - pip install poetry
  - poetry install -vvv
script:
  - poetry run coverage run --source=hogwarts_apitest -m pytest discover
  - poetry run coverage report -m
